# h2
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tricount-api
    username: sa
    password:

  sql:
    init:
      mode: always

# spring -h2
logging:
  level:
    org.springframework.jdbc: debug